### ISSUE TITLE
[Bug]:Issue with report creation command

### ISSUE THREAD

**Issue by DhruvilDhulia4250** [eighty9nine/filament-reports#1]
### What happened?

When I am referring to your documentation there is a command to create the report while I have used this command there is an error while running this command. After that, I used the command php artisan make:filament-report StocksReport, and then the stock report file was created.

### How to reproduce the bug

First I install the package. After that, I publish the configuration. After that, I have added the plugins to the AdminPanelProvider and then create the file using "php artisan make:report UsersReport" then it showing error.

### Package Version

3.0

### PHP Version

8.1

### Laravel Version

10.0

### Which operating systems does with happen with?

Linux

**Comment by adnanyalahow** [comment]
same here   there is an error when installing  
 Method Filament\Panel::getTenantRoutePrefix does not exist.

  at vendor\filament\support\src\Concerns\Macroable.php:72
     68▕     {
     69▕         $macro = static::getMacro($method);
     70▕
     71▕         if ($macro === null) {
  ➜  72▕             throw new BadMethodCallException(sprintf(
     73▕                 'Method %s::%s does not exist.',
     74▕                 static::class,
     75▕                 $method,
     76▕             ));

**Comment by RI5HIT** [comment]
@DhruvilDhulia4250 The correct command is `php artisan make:filament-report MyFirstReport`, seems like the documentation on GitHub is not in sync, you can refer to this docs https://filament-reports.eightynine.dev/docs/getting-started.

**Comment by DhruvilDhulia4250** [comment]
@RI5HIT okay thanks

**Comment by eighty9nine** [comment]
I have updated the Github readme. Thank you @RI5HIT
