### ISSUE TITLE
[Dude]: How to obtain the information in the body of the report

### ISSUE THREAD

**Issue by intelguasoft** [eighty9nine/filament-reports#10]
### What happened?

Brother, I need to use your plugin for reports, but I can't find the way to show the data, according to the documentation I must have those two methods/functions `fn(?array $filters) => $this->registrationSummary($filters)` which is not clear at all, is there any information that you can provide me or at least you could share the source code of the demo to see how to send that information to the body of the report.

### How to reproduce the bug

It's not a failure, just a question of how it works

### Package Version

3.0.7

### PHP Version

8.3

### Laravel Version

10.x

### Which operating systems does with happen with?

Windows

### Notes

In advance I apologize for my request, as well as thanks for your collaboration to the open source world.

Greetings from our beautiful Guatemala

**Comment by webmaster254** [comment]
Hello @intelguasoft , You are supposed to create a function to get the data. like in this case f`n(?array $filters) => $this->registrationSummary($filters)` create registrationSummary function that returns data that will be displayed in your table. Hope that helps

**Comment by eighty9nine** [comment]
You can complete replace this function call:
fn(?array $filters) => $this->registrationSummary($filters)

With something like:
``` php
fn(?array $filters) => \App\Models\Post::query()
                 ->where( "status", $filters["status"])
                 ->get();
 ```
Or
```php
function ( ?array $filters): \Illuminate\Support\Collection {
      $data = [
             [ "name"=>"Eighty nine", "age"=>89],
             [ "name"=>"Peter Parker", "age"=>21]
      ]; 

      return collect($data);
}
```
The most important thing is that your function must return a normal collection or an eloquent collection. I hope this clears your concern, I will also do my best to update the documentation accordingly.
