### ISSUE TITLE
[Bug]: FYI, demo is down

### ISSUE THREAD

**Issue by ruzzzz6312** [eighty9nine/filament-reports#11]
### What happened?

Throws an exception on demo website:
https://filament-reports.eightynine.dev/demo/login
SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'

### How to reproduce the bug

Open: https://filament-reports.eightynine.dev/demo/login

### Package Version

3.0.9

### PHP Version

8.2.0

### Laravel Version

10

### Which operating systems does with happen with?

macOS, Windows, Linux

### Notes

Hey, simple note here, thanks

**Comment by eighty9nine** [comment]
@ruzzzz6312 the issue has been resolved

**Comment by ruzzzz6312** [comment]
thanks

**Comment by neuroticimbecile** [comment]
The demo site is not showing an SQL error anymore.  Thank you.
However the default username "demo@reports.com" and password are not accepted.
Error message is: " These credentials do not match our records."

**Comment by eighty9nine** [comment]
Hello @neuroticimbecile, apparently, someone edit the email of the demo user! It is resolved now
