### ISSUE TITLE
[Bug]: How to change navigation label and group

### ISSUE THREAD

**Issue by AliSuliman01** [eighty9nine/filament-reports#13]
### What happened?

I can't change the navigation label and group using typical filament methods.

### How to reproduce the bug

```
class CustomersReport extends Report
{
    ...

    public static function getNavigationGroup(): ?string
    {
        return 'Navigation Group';
    }
    public static function getNavigationLabel(): string
    {
        return 'Navigation Label';
    }

    ...
```

### Package Version

3.0.10

### PHP Version

8.2.0

### Laravel Version

10.48.10

### Which operating systems does with happen with?

Windows

**Comment by alexb34n** [comment]
Experiencing same issue here.

**Comment by eighty9nine** [comment]
This has been fixed in the latest release
