### ISSUE TITLE
How To display columns and value from database in table on reports

### ISSUE THREAD

**Issue by henilcodes** [eighty9nine/filament-reports#14]
### What happened?

`<?php

namespace App\Filament\Reports;

use App\Models\User;
use EightyNine\Reports\Report;
use EightyNine\Reports\Components\Body;
use EightyNine\Reports\Components\Footer;
use EightyNine\Reports\Components\Header;
use EightyNine\Reports\Components\Text;
use EightyNine\Reports\Components\VerticalSpace;
use Filament\Forms\Components\Select;
use Filament\Forms\Form;
use Symfony\Component\Console\Input\Input;

class UserReport extends Report
{
    public ?string $heading = "Report";

    public ?string $subHeading = "A great report";

    public function header(Header $header): Header
    {
        return $header
            ->schema([
                Header\Layout\HeaderRow::make()
                    ->schema([
                        Header\Layout\HeaderColumn::make()
                            ->schema([
                                Text::make("User Report")->title()->primary(),
                                Text::make("A user report")->subtitle(),
                            ]),
                    ]),

            ]);
    }

    public function body(Body $body): Body
    {
        return $body
            ->schema([
                Body\Layout\BodyColumn::make()
                    ->schema([
                        Text::make("name"),
                        Text::make("email"),
                        Body\Table::make()
                            ->data(
                                fn (?array $filters) => $this->registrationSummary($filters)
                            ),
                    ]),
            ]);
    }

    public function registrationSummary($filters)
    {
        $users = User::where('deleted_at', null)->get();

        return $users;
    }

    public function footer(Footer $footer): Footer
    {
        return $footer
            ->schema([
                Footer\Layout\FooterRow::make()
                    ->schema([
                        Footer\Layout\FooterColumn::make()
                            ->schema([
                                Text::make("Generated on: " . now()->format('Y-m-d H:i:s')),
                            ])->alignRight(),
                    ]),
            ]);
    }

    public function filterForm(Form $form): Form
    {
        return $form
            ->schema([
                Select::make('status')
                    ->placeholder('Status')
                    ->options([
                        'active' => 'Active',
                        'inactive' => 'Inactive',
                    ]),
            ]);
    }
}
`

### How to reproduce the bug

how display user name , email or other field.

Current report image  is

Problem is it display 1 only 

![Screenshot from 2024-05-14 20-47-31](https://github.com/eighty9nine/filament-reports/assets/99518388/32be4603-e650-419d-8632-aca6c8286dff)

### Package Version

3.0

### PHP Version

8.2

### Laravel Version

11.0

### Which operating systems does with happen with?

Linux

**Comment by HENILCODES** [comment]
$body ->schema([

 Body\Layout\BodyColumn::make() ->schema([ Text::make("email"), Body\Table::make() ->data( fn (?array $filters) => $this->registrationSummary($filters) ), ]), 

Body\Layout\BodyColumn::make() ->schema([ 
Text::make("name"),  Body\Table::make()->data( fn (?array $filters) => $this->registrationSummary($filters)), 

]),


]);

**Comment by eighty9nine** [comment]
Use this instead
```php

use EightyNine\Reports\Components\Body\TextColumn;

public function body(Body $body): Body
{
    return $body
        ->schema([
            Body\Layout\BodyColumn::make()
                ->schema([
                    Body\Table::make()
                        ->columns([
                                 TextColumn::make("email"),
                                 TextColumn::make("name")
                        ])
                        ->data(
                            fn (?array $filters) => $this->registrationSummary($filters)
                        ),
                ]),
        ]);
}

**Comment by bhattji** [comment]
How to get the columns from the master table related with foreign key?

For example I have location_id in my User object, and in my resource I use location.name to get the name of the location, but that does not work in report.

**Comment by HENILCODES** [comment]
Bro You are creater of that package.
I don't know about your question.

You have some demo code of that package please give me. I want create reports.

**Comment by eighty9nine** [comment]
That won't, the idea behind the report is that it displays aggregate or summarized data. So, the output to be display cannot contain relationships. A quick solution would be to add a location name column(redundancy or denormalization) or use a join.

```php

User::where('deleted_at', null)
    ->join("locations", "location.id", "=", "users.location_id")
    ->select("users.name", "users.email", "locations.name")
    ->get();
```

But also, I am also working on adding the support for relationships, I will release this update in a few weeks

**Comment by eduardocm2002** [comment]
How to display the table view by pages when there are thousands of records but when printing it does so with all the records
