### ISSUE TITLE
[Bug]: Demo is down

### ISSUE THREAD

**Issue by zajinx** [eighty9nine/filament-reports#16]
### What happened?

Demo is down, can we get a repo link?

### How to reproduce the bug

when i visit https://filament-reports.eighty9.dev/demo it complains DNS_PROBE_FINISHED_NXDOMAIN

### Package Version

3

### PHP Version

8.2

### Laravel Version

9.00

### Which operating systems does with happen with?

Windows

**Comment by eighty9nine** [comment]
That link is wrong, the correct url is https://filament-reports.eightynine.dev/demo
