### ISSUE TITLE
Docs update

### ISSUE THREAD

**Issue by Zacktamondo** [eighty9nine/filament-reports#18]
### What happened?

How can I contribute to the docs?

### How to reproduce the bug

Open the docs and check it.

### Package Version

3.0.10

### PHP Version

8.3.0

### Laravel Version

11.0

**Comment by eighty9nine** [comment]
I see you have successfully contributed, very highly appreciated 🙏🏽

**Comment by Zacktamondo** [comment]
You are welcome, but I meant this [docs](https://filament-reports.eightynine.dev/docs).

**Comment by eighty9nine** [comment]
Please use this repo https://github.com/eighty9nine/filament-reports-demo
