### ISSUE TITLE
[Bug]: Actions

### ISSUE THREAD

**Issue by zajinx** [eighty9nine/filament-reports#19]
### What happened?

I don't see any documentation on how you handle the export button, can you please update the docs or point me in the right direction

### How to reproduce the bug

i don't see any option to add the export button like in your demo or screenshots

### Package Version

3

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

Windows

**Comment by eighty9nine** [comment]
Hello @zanjix, currently the plugin does not support exporting. We are working in adding that feature!
