### ISSUE TITLE
[Query]: How to access filter values outside table?

### ISSUE THREAD

**Issue by skills-up** [eighty9nine/filament-reports#20]
### What happened?

I have defined filters, and want to use their values outside tables. Such as for displaying selected dates in the header.
How can I do that?

### How to reproduce the bug

N/A

### Package Version

3.0.10

### PHP Version

8.2.18

### Laravel Version

11.8.0

### Which operating systems does with happen with?

macOS

**Comment by eighty9nine** [comment]
Let me work on this and get back to you

**Comment by eighty9nine** [comment]
You can use anywhere the `reports()->getFilterState()` anywhere in the report class to get the filter state. The method returns an array with form values as keys.
