### ISSUE TITLE
[Question]: Print or export to pdf?

### ISSUE THREAD

**Issue by aeq-dev** [eighty9nine/filament-reports#21]
### What happened?

Is there a way to preview report in a single blade page in order to print it or export to pdf?

### How to reproduce the bug

-

### Package Version

-

### PHP Version

-

### Laravel Version

-

**Comment by eighty9nine** [comment]
This feature is currently not supported, I am working on it

**Comment by eighty9nine** [comment]
I have added ability to directly print. You can convert to pdf as well in the print window! @aeq-dev

**Comment by skills-up** [comment]
How can this ability be used? Is there a way to add a print button next to filter button?

**Comment by eighty9nine** [comment]
There should be a cog icon to the right of the filters Title in the filters form, when you click it opens a dropdown which contains option to print, please report if the options doesn't appear even when you have update to the latest version

**Comment by skills-up** [comment]
The option does appear. However, is there a way to have it as a button next to filter button?

**Comment by eighty9nine** [comment]
I understand you now, you mean below the form, that is not possible for now, but I will add that customization in the next update within a few days
