### ISSUE TITLE
 [Bug]: [Missing parameter: tenant]

### ISSUE THREAD

**Issue by shamyusof** [eighty9nine/filament-reports#3]
### What happened?

Missing required parameter for [Route: filament.admin.reports.users-report] [URI: admin/reports/branch/{tenant}/users-report] [Missing parameter: tenant].

### How to reproduce the bug

First I install the package. After that, I publish the configuration. After that, I have added the plugins to the AdminPanelProvider and then create the file using "php artisan make:filament-report UsersReport" then it showing error.

### Package Version

3.0.6

### PHP Version

8.2

### Laravel Version

10.0

### Which operating systems does with happen with?

Windows

**Comment by eighty9nine** [comment]
Can you please share the full error stack here? @shamyusof

**Comment by bercksonjohnslyjeanlouis** [comment]
Facing the same problem. It does not work on tenant mode... Seems that the problem is occurred from the routes of the plugin !

**Comment by swapneal-dev** [comment]
I have opened a pull request to solve this issue. If you want a temporary solution, look at the PR. @bercksonjohnslyjeanlouis @shamyusof

**Comment by bercksonjohnslyjeanlouis** [comment]
Thank you @swapneal-dev. I'm going to take a look.

**Comment by shamyusof** [comment]
> I have opened a pull request to solve this issue. If you want a temporary solution, look at the PR. @bercksonjohnslyjeanlouis @shamyusof

it work!! thank you @swapneal-dev

**Comment by eighty9nine** [comment]
Thank you @swapneal-dev , the fix is available in version 3.0.10
