### ISSUE TITLE
[Bug]: Demo Link is not working

### ISSUE THREAD

**Issue by pa2codes** [eighty9nine/filament-reports#5]
### What happened?

Can't access the demo

### How to reproduce the bug

Click on the demo link

### Package Version

latest

### PHP Version

latest

### Laravel Version

latest

**Comment by eighty9nine** [comment]
This has been fixed.

**Comment by dennisoderwald** [comment]
@eighty9nine The demo link is still (or again) not working

**Comment by eighty9nine** [comment]
I have confirmed just now that it works perfectly

**Comment by dennisoderwald** [comment]
In the README (https://github.com/eighty9nine/filament-reports/blob/main/README.md) the following link (https://reports-demo.eightynine.dev/demo) is given, this seems like a local environment to me. :)

**Comment by eighty9nine** [comment]
Makes sense, it's a typo I have to fix real quick
