### ISSUE TITLE
[Bug]: Text::make not working

### ISSUE THREAD

**Issue by dursuntokgoz** [eighty9nine/filament-reports#7]
### What happened?

Text::make and image::make is not working

### How to reproduce the bug

Text::make and image::make is not working

### Package Version

Main

### PHP Version

8.2

### Laravel Version

10.x

### Notes

Text::make and image::make is not working

**Comment by dursuntokgoz** [comment]
use EightyNine\Reports\Components\Text;
use EightyNine\Reports\Components\Image;

**Comment by eighty9nine** [comment]
Can you please share the report class in which it fails

**Comment by eighty9nine** [comment]
Closed due to lack of clarification
