### ISSUE TITLE
[Bug]: Missing HasLineClamp Trait

### ISSUE THREAD

**Issue by dursuntokgoz** [eighty9nine/filament-reports#8]
### What happened?

I'm encountering an error while using the "Body" component of your package. It indicates that the "HasLineClamp" trait is required for the report, but this trait seems to be missing in the package.

### How to reproduce the bug

Check for Missing Trait: Please review the package contents to confirm if the "HasLineClamp" trait is indeed missing.

Verify Update Status: Check if you are using the latest version of the package. Perhaps, a recent update has addressed this missing trait issue.

Explore Alternative Solutions: If it's confirmed that the trait is missing, investigate if there's another way to address this absence or consider alternative methods for generating reports.

### Package Version

3.0

### PHP Version

8.1.26

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by peterk636** [comment]
I have the same issue. Any suggestions how to fix this?

**Comment by dursuntokgoz** [comment]
Yes HasLineClamp delete row. Or comment row

https://github.com/eighty9nine/filament-reports/blob/7067540dc8a935b3cfcaa86c74513005c615b202/src/Components/Body/TextColumn.php#L21

**Comment by eighty9nine** [comment]
This has been fixed
