### ISSUE TITLE
[Bug]: Not compatible with Laravel 11.2.x / Filament 3.2.x?

### ISSUE THREAD

**Issue by goyne** [eighty9nine/filament-reports#9]
### What happened?

Not compatible with Laravel 11.2 / Filament 3.2.63?

Trying to install the package on a Laravel environment 11.2.0 with Filament 3.2.63, but it returns an error, referring to the illuminate/contracts package:

eightynine/filament-reports[3.0.1, ..., 3.0.7] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.

### How to reproduce the bug

Try to install on an environment running the latest version of Laravel with the latest version of Filament.

### Package Version

3.0.7

### PHP Version

8.2.15

### Laravel Version

11.2.0

### Which operating systems does with happen with?

macOS

**Comment by lodekib** [comment]
Facing the same issue as well.

**Comment by eighty9nine** [comment]
I have update the package to support 11.x
